// 术语链接，文档中一律写为 [动画编辑](${docs})
// 逻辑中按照此表替换为 [动画编辑](URL + /animation-animator/ + language + .md)
// const LinkMap = {
// "动画编辑":"${docs}animation-animator",
// "精灵":"${docs}graphics-sprite",
// "场景管理":"${docs}core-scene",
// "资源管理":"${docs}resource-manager",
// "场景":"${docs}core-scene",
// "变换":"${docs}core-transform",
// "环境光":"${docs}graphics-light",
// "引擎":"${docs}core-engine",
// "相机":"${docs}graphics-camera",
// "光照":"${docs}graphics-light",
// "脚本":"${docs}script",
// "内置几何体":"${docs}graphics-model",
// "材质":"${docs}graphics-material",
// "数学库":"${docs}core-math",
// "Texture":"${docs}graphics-texture",
// "Sprite":"${docs}graphics-sprite",
// "Atlas 图集":"${docs}graphics-sprite-atlas",
// "帧动画":"${docs}editor-frame-animation",
// "动画片段编辑":"${docs}animation-clip",
// "精灵遮罩组件":"${docs}graphics-sprite-mask",
// "碰撞器":"${docs}physics-collider",
// "事件系统":"${docs}script-communication",
// "动画组件":"${docs}animation-system",
// "clone":"${docs}core-entity-clone",
// "渲染":"${docs}mesh-renderer",
// "物理":"${docs}physics-overall",
// "动画":"${docs}animation-system",
// "交互":"${docs}input",
// "Doc":"${docs}controls",
// "Doc":"${docs}input-framebuffer-picker",
// "Doc":"${docs}performance-stats",
// "支付宝/淘宝小程序":"${docs}miniprogram",
// "鼠标与触控":"${docs}input",
// "PhysX":"${docs}physics-overall",
// "纯色背景":"${docs}graphics-background-solidColor",
// "纹理背景":"${docs}graphics-background-texture",
// "天空背景":"${docs}graphics-background-sky",
// "天空盒":"${docs}graphics-background-sky",
// "脚本生命周期时序图":"${docs}script",
// "相机组件":"${docs}graphics-camera-component",
// "相机控件":"${docs}graphics-camera-control",
// "网格渲染器":"${docs}graphics-model-mesh",
// "教程":"${docs}graphics-material",
// "glTF":"${docs}graphics-gltf",
// "导出 Unlit 材质到引擎":"${docs}graphics-material-Unlit",
// "直接光与环境光":"${docs}graphics-light",
// "立方纹理":"${docs}graphics-texture-cube",
// "glTF 文件":"${docs}graphics-gltf",
// "《C4D 烘焙教程》":"${docs}graphics-bake-c4d",
// "《Blender 烘焙教程》":"${docs}graphics-bake-blender",
// "《导出 Unlit 材质》":"${docs}graphics-material-Unlit",
// "光照教程":"${docs}graphics-light",
// "Unlit 材质":"${docs}graphics-material-Unlit",
// "IBL":"${docs}graphics-light",
// "环境光的 IBL 模式":"${docs}graphics-light",
// "烘焙教程":"${docs}graphics-bake-blender",
// "资源管理器":"${docs}resource-manager",
// "导出 Unlit 教程":"${docs}graphics-material-Unlit",
// "Blinn-Phong 材质":"${docs}graphics-material-BlinnPhong",
// "PBR 材质":"${docs}graphics-material-PBR",
// "自定义材质":"${docs}graphics-custom-material",
// "ModelMesh":"${docs}graphics-model-mesh",
// "BufferMesh":"${docs}graphics-buffer-mesh",
// " glTF 格式":"${docs}graphics-gltf",
// "ResourceManager":"${docs}resource-manager",
// " glTF 资源":"${docs}graphics-gltf",
// "网格":"${docs}graphics-mesh",
// "**组件**":"${docs}component",
// "资源加载":"${docs}resource-manager",
// "Texture2D":"${docs}graphics-texture-2d",
// "Entity":"${docs}core-entity",
// "SpriteMask":"${docs}graphics-sprite-mask",
// "Texture":"${docs}graphics-texture-2d",
// "资源加载教程":"${docs}resource-manager#内置资源类型",
// "项目发布":"${docs}interface-publish",
// "2D 纹理":"${docs}graphics-texture-2d",
// "射线包围盒":"${docs}physics-manager#使用射线检测",
// "脚本组件生命周期":"${docs}script#组件生命周期函数",
// "资产面板":"${docs}interface-assets",
// "检查器面板":"${docs}interface-inspector",
// "主编辑区":"${docs}interface-viewport",
// "代码编辑器":"${docs}script-edit",
// "纹理压缩":"${docs}graphics-texture-compression",
// "onTriggerEnter":"${docs}script#组件生命周期函数#ontriggerenter",
// "onTriggerStay":"${docs}script#组件生命周期函数#ontriggerstay",
// "onTriggerExit":"${docs}script#组件生命周期函数#ontriggerexit",
// "onCollisionEnter":"${docs}script#组件生命周期函数#oncollisionenter",
// "onCollisionStay":"${docs}script#组件生命周期函数#oncollisionstay",
// "onCollisionExit":"${docs}script#组件生命周期函数#oncollisionexit",
// "参考":"${docs}input",
// "Loader":"${docs}resource-manager",
// "脚本组件":"${docs}script",
// "压缩纹理":"${docs}graphics-texture-compression",
// "生命周期函数":"${docs}script#组件生命周期函数",
// "事件通信":"${docs}script-communication",
// "创建脚本":"${docs}script-create",
// "内置组件":"${docs}core-component",
// "输入交互":"${docs}input",
// "实体":"${docs}core-entity",
// }